### ISSUE TITLE
Keep having error on username and password

### ISSUE THREAD

**Issue by vshy108** [MOLPay/molpay-mobile-xdk-reactnative-beta#1]
I have the sandbox merchant account but I don't know where to obtain the mp_username value which is mandatory input to use this molpay xdk, may I know how can get the username from the sandbox webpage? or it is same value with the mp_merchant_ID?

**Comment by clewlb** [comment]
@vshy108, thanks for trying out our XDK, please email to our support@molpay.com, provide your merchant information along and request the credentials for the XDK.
