### ISSUE TITLE
Cannot alert after change from background to foreground mode in IOS

### ISSUE THREAD

**Issue by hiyshamx** [MOLPay/molpay-mobile-xdk-reactnative-beta#10]
The issue is when user tap home button during molpay window is open . Its like the user want to cancel the payment then he/she tap the phone home button and then the app state become background mode. After  that the user open back the app and the same molpay window came out. Then, the user tap close button in the top right of the molpay window, and if there's error, the alert will show but seems like the  alert method is broken. Tested in IOS only.
Please refer the screenshot below

![screen shot 2017-10-20 at 10 02 56 pm](https://user-images.githubusercontent.com/6882177/31824900-13aa826a-b5e3-11e7-8c17-4e0ed51313bc.png)

**Comment by LeowWH** [comment]
Hi @nikhiysham,

We have update our XDK to 0.16.2 to solve this problem.

Thanks.
