### ISSUE TITLE
Cannot run on android after updating to latest xdk

### ISSUE THREAD

**Issue by hiyshamx** [MOLPay/molpay-mobile-xdk-reactnative-beta#11]
Hi,

Giving the error below on my mac terminal by running the command react-native run-android --variant=release after updating to the latest xdk version 16.

Please help me. Critical , the users has been complaining cannot made a payment since last week after Molpay doing disaster recovery and update some of the xdk part and need to update xdk ASAP.

Thank you

![screen shot 2017-10-22 at 4 07 38 pm](https://user-images.githubusercontent.com/6882177/31859844-a5e445c4-b743-11e7-81fb-8f15340d4f30.png)

**Comment by LeowWH** [comment]
Hi @nikhiysham,

Sorry for any inconvenient please update to XDK 0.16.1 and also please make sure you are using build tools version 25 in your android/app/build.gradle as below.
`
 compileSdkVersion 25
 buildToolsVersion "25.0.0"
`
Thanks.

**Comment by hiyshamx** [comment]
Hi @LeowWH , still have some issue. Please refer screenshot below

**My buildVersion**

![screen shot 2017-10-23 at 11 46 31 am](https://user-images.githubusercontent.com/6882177/31871567-de43c6ca-b7e7-11e7-9d1e-cc5bacaffd9d.png)

**Issue during run android on real device**

![screen shot 2017-10-23 at 11 45 55 am](https://user-images.githubusercontent.com/6882177/31871557-cc652192-b7e7-11e7-91ae-94321a744484.png)

**Comment by hiyshamx** [comment]
Oh.sorry, i'm using RN version below 47, added createJSModule worked for me. Solved.
