### ISSUE TITLE
Pending transaction issue

### ISSUE THREAD

**Issue by hiyshamx** [MOLPay/molpay-mobile-xdk-reactnative-beta#12]
I'm not sure whether this sdk give me the correct response or not. Last sunday (22 October 2017),  user made a complain about the booking. His account has been deducted but the response from molpay is error and the record has been mark as failed  in merchant account until today i checked in merchant account the payment has been  captured even the last sunday  the payment transaction has failed. Please advice to me how to tackle this problem, since today i have a total of around 10 users reporting the same problem and in the screenshot below is 1 of them 

Refer to the below screenshot

![screen shot 2017-10-23 at 12 58 03 pm](https://user-images.githubusercontent.com/6882177/31919588-2c589756-b896-11e7-9e37-14584934bcda.png)

![screen shot 2017-10-24 at 8 34 48 am](https://user-images.githubusercontent.com/6882177/31919599-3eeeeeb0-b896-11e7-877c-a57305acbbcd.png)

**Comment by LeowWH** [comment]
Hi @nikhiysham,

This issue is not related to our XDK you can email to our support@molpay.com to get more information and get some advise from our support.

Thanks.

**Comment by hiyshamx** [comment]
Noted
