### ISSUE TITLE
Molpay xdk return error message "Transaction not found" after user successfully paid

### ISSUE THREAD

**Issue by hiyshamx** [MOLPay/molpay-mobile-xdk-reactnative-beta#13]
Hi,

Why xdk return error message "Transaction not found" after user successfully made payment (the user who had problem mainly using fpx). After the user had successfully made payment (for eg: using fpx maybank2u) and click continue with transaction , the response return by xdk is "Transaction not found" rather than success (status_code = "00"). Unfortunately this happened intermittent. Please help me. .

Thanks,

**Comment by clewlb** [comment]
@nikhiysham,

This is a transaction issue, please forward your message to our support at support@molpay.com, so we can provide a better support to you there.

Thank you.
