### ISSUE TITLE
cannot find symbol new MOLPayReactPackage()

### ISSUE THREAD

**Issue by LeoLaiFookSiang** [MOLPay/molpay-mobile-xdk-reactnative-beta#14]
Hi, I am facing an error cannot find symbol new MOLPayReactPackage(), I have follow all the step listed in documentation to implement it. My 
    compileSdkVersion 25
    buildToolsVersion "25.0.0"

**Comment by LeowWH** [comment]
Hi @LeoLaiFookSiang ,

Have you import our library in your MainApplication.java as below before using "new MOLPayReactPackage()"?

`import com.molpayxdk.MOLPayReactPackage;`

If yes please try out our ExampleProject and let us know the result thanks.

**Comment by LeoLaiFookSiang** [comment]
Thanks, it show my problem
