### ISSUE TITLE
Android unable to make payment

### ISSUE THREAD

**Issue by LeoLaiFookSiang** [MOLPay/molpay-mobile-xdk-reactnative-beta#15]
Hi, this plugin is works on IOS. But for android, after I fill in my VISA card details, it stop at finalising payment status. Please help

**Comment by LeowWH** [comment]
Hi @LeoLaiFookSiang ,

Please update to our latest version which is 0.17.0 by using `npm install molpay-mobile-reactnative-beta@0.17.0` and try again thanks.
