### ISSUE TITLE
How to set extra param

### ISSUE THREAD

**Issue by hiyshamx** [MOLPay/molpay-mobile-xdk-reactnative-beta#16]
Is there any place where i can set an extra parameters to the payment request ?

**Comment by clewlb** [comment]
@nikhiysham,

We don't quite get your concerns with the questions you put up, and we assume that all available parameters are published on the repo readme under the subject "Prepare the payment detail object", here's the readme again for your reference, https://github.com/MOLPay/molpay-mobile-xdk-reactnative-beta/blob/master/README.md. If you think we missed your question, please state the extra parameters you mentioned specifically so we can answer your question more accurately. In order for us to assist you better on your request, please email to mobile@molpay.com and state your question in more detail.

Thank you.

**Comment by hiyshamx** [comment]
Hi,

sorry for my previous question. My question is can i put an extra parameter in payment detail object, for eg 'user_id : "test"' so that i can retrieve it later during server-to-server communication in order to identify the user.

I assume based on your answer previously, it is prohibited

**Comment by LeowWH** [comment]
Hi @nikhiysham ,

Yes you are able to do put "extra parameter" you mean in the payment object, our XDK won't restrict on it but during server to server communication you are not able to get your "extra parameter" on your server the payment object will only left in your payment object and your app it will not send by our server to your server thanks.
