### ISSUE TITLE
Access denied, please check merchant id, app name, or verification key

### ISSUE THREAD

**Issue by RORrvtech** [MOLPay/molpay-mobile-xdk-reactnative-beta#17]
contacted support many times. 
i am using "molpay-mobile-xdk-reactnative-beta": "^0.17.0"
cross checked all creads many times that was povided by molpay.

var paymentDetails = {
    // Mandatory String. A value more than '1.00'
    'mp_amount': order.amount || '1.1',
    // Mandatory String. Values obtained from MOLPay
    'mp_username': creads['MP_USERNAME'],
    'mp_password': creads['MP_PASSWORD'],
    'mp_merchant_ID': creads['MP_MERCHANT_ID'],
    'mp_app_name': creads['MP_APP_NAME'],
    'mp_verification_key': creads['MP_VERIFICATION_KEY'],

    // Mandatory String. Payment values
    'mp_order_ID': (order.order_id),
    'mp_currency': 'MYR',
    'mp_country': 'MY',

    // Optional String.
    'mp_channel': '' + (order.bankcode), // Use 'multi' for all available channels option. For individual channel seletion, please refer to "Channel Parameter" in "Channel Lists" in the MOLPay API Spec for Merchant pdf. 
    'mp_bill_description': '' + (description),
    'mp_bill_name': 'anyname',
    'mp_bill_email': '' + (email),
    'mp_channel_editing': false, // Option to allow channel selection.
    'mp_editing_enabled': false, // Option to allow billing information editing.

    // Optional for Escrow
    'mp_is_escrow': '1', // Optional for Escrow, put "1" to enable escrow

    // For transaction request use only, do not use this on payment process
    'mp_transaction_id': '', // Optional, provide a valid cash channel transaction id here will display a payment instruction screen.
    'mp_request_type': '', // Optional, set 'Status' when doing a transactionRequest

    // Optional, use this to customize the UI theme for the payment info screen, the original XDK custom.css file is provided at Example project source for reference and implementation. Required cordova-plugin-file to be installed
    'mp_custom_css_url': '',

    // Optional, set the token id to nominate a preferred token as the default selection, set "new" to allow new card only
    'mp_preferred_token': '',

    // Optional, credit card transaction type, set "AUTH" to authorize the transaction
    'mp_tcctype': '',

    // Optional, set true to process this transaction through the recurring api, please refer the MOLPay Recurring API pdf  
    'mp_is_recurring': false,

    // Optional for sandboxed development environment, set boolean value to enable.
    'mp_sandbox_mode': false,

    // Optional, required a valid mp_channel value, this will skip the payment info page and go direct to the payment screen.
    'mp_express_mode': false,

    // Optional, enable this for extended email format validation based on W3C standards.
    'mp_advanced_email_validation_enabled': true,
    
    // Optional, enable this for extended phone format validation based on Google i18n standards.
    'mp_advanced_phone_validation_enabled' : false,

    // Optional, explicitly force disable billing name edit.
    'mp_bill_name_edit_disabled': false,

    // Optional, explicitly force disable billing email edit.
    'mp_bill_email_edit_disabled': false,

    // Optional, explicitly force disable billing mobile edit.
    'mp_bill_mobile_edit_disabled': false,

    // Optional, explicitly force disable billing description edit.
    'mp_bill_description_edit_disabled': false,

    // Optional, EN, MS, VI, TH, FIL, MY, KM, ID, ZH.
    'mp_language': "EN",

    // Optional, enable for online sandbox testing.
    'mp_dev_mode': false
  };

sample object i am passing. 
please help. i am not able to use molapay any further.

Hi Merchant zivvies,

Kindly be inform we have rectify the said issue from our end. We advise you to retry again from your end.

Please refer below login to ensure that you are able to access the app accordingly:
======================
Appname : *******
username : api_*******
password : api_*******
=======================

Should you have any inquiries please do not hesitates to contact us.

**Comment by clewlb** [comment]
@RORrvtech,

Please send us the exact values (not the variable names) you put for the payment details to mobile@molpay.com, and we will take it from there.

Thanks.

**Comment by RORrvtech** [comment]
sent,waiting for response. hope it will get resolve

**Comment by RORrvtech** [comment]
Issue resolved (For the help of developer who are getting the same issue )
please ensure that email address is valid (it cannot contain  + ). 
mobile numbers need to be valid also.

Thanks for the quick response.
