### ISSUE TITLE
Android back button to cancel but molpay return status code 00 (Success)

### ISSUE THREAD

**Issue by LeoLaiFookSiang** [MOLPay/molpay-mobile-xdk-reactnative-beta#18]
Hi, I am facing 1 issue, I was tested yesterday morning if I use android to top up, and press back button to cancel it will return me status code 11, but start from yesterday 4pm when I press back button it return me status code 00. Please help, thanks

**Comment by clewlb** [comment]
@LeoLaiFookSiang, please check the order id and the transaction id. The result always returned for the last transaction made for the same order id (in repeated use). Thanks.
