### ISSUE TITLE
Android Installation return 'No resource found that matches the given name: attr 'andorid:keyboardNavigationCluster'

### ISSUE THREAD

**Issue by unpokolokko** [MOLPay/molpay-mobile-xdk-reactnative-beta#19]
I followed all the instruction stated and when run, it fails and I got this message instead : 

![screen shot 2018-02-08 at 8 59 51 am](https://user-images.githubusercontent.com/33192514/35949855-992c1562-0cae-11e8-91a2-46e4bb6d90f7.png)
![screen shot 2018-02-08 at 9 00 13 am](https://user-images.githubusercontent.com/33192514/35949859-9f6346b2-0cae-11e8-842a-abe4478b70aa.png)

**Comment by clewlb** [comment]
@unpokolokko, please folk our repo and try to reproduce the exception on our example project and share with us. Then we'll take it further from here. Thanks.
