### ISSUE TITLE
Android Low Performance

### ISSUE THREAD

**Issue by maplerichie** [MOLPay/molpay-mobile-xdk-reactnative-beta#20]
Is this Molpay UI using webview? There are some lagging on my Android device

react-native-cli: 2.0.1
react-native: 0.55.2
compileSdkVersion 26
buildToolsVersion '26.0.2'
minSdkVersion 16
targetSdkVersion 26

Android: HTC One M8

**Comment by clewlb** [comment]
@maplerichie, please send an email to mobile@molpay.com and tell us as detail as possible for your problems. We will take it from there. And yes, the XDK uses the webview component, and we have already maximized our codes to the best performance you can get on the webview. Any insatisfaction would mean a complaint directly pointed to Google Android tech instead. Thanks for your feedback though.

**Comment by maplerichie** [comment]
@clewlb 
Noted. Because I tot this plugin is using React Native to render native UI. So it is weird to have low performance issue. But if it using webview then it may true as the webview still having low performance in certain low specs/old Android devices.
I'm not here to complain anyway. TQ
