### ISSUE TITLE
Molpay SDK for Android (React)

### ISSUE THREAD

**Issue by nzrin** [MOLPay/molpay-mobile-xdk-reactnative-beta#22]
I got some weird issues. 

1. When I try follow step 2 (Copy onActivityResult etc.. inside MainActivity). It works fine yes I can load Molpay modal. But I got another issues, it seems that by adding step 2 in MainActivity, it cause my image picker, google place picker not return any value. 

2. When I try to follow step 2 (Copy onActivityResult etc.. inside MainApplication). Molpay modal doesnt trigger/not working. 

3. Is there any workaround to put step 2 in another classes instead of MainActivity? It messes with my Navigation.

Thanks.

**Comment by LeowWH** [comment]
Hi @nzrin ,

Please try the newest version 0.18.4 by using `npm install molpay-mobile-xdk-reactnative-beta@0.18.4 --save` and give us know the result. And please also follow our new Android setup step thanks.

**Comment by nzrin** [comment]
Thank you! It works great now!
