### ISSUE TITLE
NSAllowsArbitraryLoads requirement might get rejected by applestore

### ISSUE THREAD

**Issue by badoet** [MOLPay/molpay-mobile-xdk-reactnative-beta#23]
May we know why this setting in info.plist is required?
https://stackoverflow.com/questions/31534304/does-app-store-reject-submission-if-nsallowsarbitraryloads-set-to-yes

the app store might reject apps with this setting turned on

any input on this?
thank you

**Comment by clewlb** [comment]
You may ignore the "App Transport Security Settings" as it was part of the legacy we had for supporting some resources like images that weren't downloaded from the https sites. Btw, having the setting added won't cause APP STORE rejection.
