### ISSUE TITLE
Error while tapping on pay button (iOS)

### ISSUE THREAD

**Issue by avoidchanges** [MOLPay/molpay-mobile-xdk-reactnative-beta#24]
![simulator screen shot - iphone 7 - 2018-12-05 at 19 36 12](https://user-images.githubusercontent.com/1065701/49511137-45e9dc00-f8c5-11e8-8614-f7d16bde5619.png)

I've got this error after triggering pay button. iOS only. Android works great. Thanks.

**Comment by LeowWH** [comment]
Hi @avoidchanges ,

Please confirm you have done step 2 to 5 for the iOS installation, and if is possible screenshot your project that include our plugin like iOS installation step 5. If you feel free please also test out our MOLPayReactExampleProject thanks.

**Comment by LeowWH** [comment]
Hi @avoidchanges ,

We are closing this issue now please feel free to reopen this issue if your problem is not yet resolved thanks.
