### ISSUE TITLE
Error running on iOS Simulator

### ISSUE THREAD

**Issue by biranchi2018** [MOLPay/molpay-mobile-xdk-reactnative-beta#25]
I am getting the below error:

Loading dependency graph, done.
error: bundling failed: TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/Users/biranchi/Desktop/MOLPay Docs/molpay-mobile-xdk-reactnative-beta-master/MOLPayReactExampleProject/node_modules/@babel/traverse/lib/scope/index.js:867:13)

**Comment by LeowWH** [comment]
@biranchi2018 ,

Not sure you have resolve your problem or not but you can try to test our example project as we cannot reproduce your issue at our side thanks.

https://github.com/MOLPay/molpay-mobile-xdk-reactnative-beta/tree/master/MOLPayReactExampleProject

**Comment by LeowWH** [comment]
Hi,

This issue is already fixed, the latest MOLPayReactExampleProject is using the latest version of react-native and is working now.
