### ISSUE TITLE
7-11 cash transaction not found on ioS

### ISSUE THREAD

**Issue by ridwan85** [MOLPay/molpay-mobile-xdk-reactnative-beta#26]
![screen shot 2019-01-21 at 1 28 50 am](https://user-images.githubusercontent.com/7012611/51442844-1891aa00-1d1c-11e9-885c-cc6c7ae353e2.png)
![screen shot 2019-01-21 at 1 28 58 am](https://user-images.githubusercontent.com/7012611/51442853-28a98980-1d1c-11e9-84b9-8b3d5f4dddc9.png)
![screen shot 2019-01-21 at 1 29 06 am](https://user-images.githubusercontent.com/7012611/51442855-30692e00-1d1c-11e9-880a-d83f4ded144a.png)

As above screenshot. 7-11 cash suddenly break on IOS. Online banking working fine

**Comment by LeowWH** [comment]
@ridwan85 ,

Please try again, this is a transaction issue and should be resolved now.

Thanks.
