### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by hpelitebook745G2** [MOLPay/molpay-mobile-xdk-reactnative-beta#28]
I was trying to integrate this into my RN project with version 0.60.5 but I got error during compilation:

`'React/RCTBridgeModule.h' file not found`

<img width="269" alt="Screen Shot 2019-09-22 at 9 00 33 AM" src="https://user-images.githubusercontent.com/27658429/65380867-721cff00-dd17-11e9-85ea-9e659c52154c.png">

I even tried it in a fresh project with the same RN version but I also got the same error. Did I miss anything or is there any additional configuration due to new RN version?

I tried running the sample app and it worked fine.

**Comment by LeowWH** [comment]
Hi @hpelitebook745G2,

This issue is due to RN > 0.60.0 have start using CocoaPods integration by default and we have update our plugin to 0.27.1 please try "npm install molpay-mobile-xdk-reactnative-beta@0.27.1" and follow the new installation step thanks.

**Comment by hpelitebook745G2** [comment]
I was setting the podspec myself similar to your new commit but I'm not quite sure why that didn't work. Anyway, this version finally fixed the iOS compilation error!
