### ISSUE TITLE
Runtime errors on both platforms for version 0.27.1 and RN 0.60.5

### ISSUE THREAD

**Issue by hpelitebook745G2** [MOLPay/molpay-mobile-xdk-reactnative-beta#29]
With my project RN version 0.60.5 as of this writing, I already compiled successfully by upgrading to `molpay-mobile-xdk-reactnative-beta@0.27.1` from [this issue](https://github.com/MOLPay/rms-mobile-xdk-reactnative-beta/issues/28).

However, after following the setup instructions I got a different runtime errors for both platforms on runtime.

For Android: 
```
{"Error":"Communication Error, please check internet connection, username, or password"}
```
<img width="311" alt="Screen Shot 2019-09-25 at 11 11 00 PM" src="https://user-images.githubusercontent.com/27658429/65614186-c3641180-dfe9-11e9-85da-b9efc5f0a884.png">

For iOS: 
```
Cannot read property 'setPaymentDetails' of undefined
```
<img width="467" alt="Screen Shot 2019-09-25 at 11 02 41 PM" src="https://user-images.githubusercontent.com/27658429/65614378-1ccc4080-dfea-11e9-9d2a-b90ccc265e09.png">

Have I missed anything?

**Comment by LeowWH** [comment]
Hi @hpelitebook745G2,

For Android:

You will need a valid merchant credentials or a sandbox credentials to use our plugin, you may send your request to sales-sa@razer.com or support-sa@razer.com to ask for one to be created for you thanks.

For iOS:

We cannot reproduce the issue even using RN 0.60.5 project. You may try to init a new plain project and try the auto link installation step. You may also wanna try to uninstall and clean all the manual installation and reinstall our plugin in your own project, then follow the auto link installation step again thanks.

**Comment by hpelitebook745G2** [comment]
It works now, thanks!
