### ISSUE TITLE
Is this library to use bank transfer with Maybank2u

### ISSUE THREAD

**Issue by rustykey** [MOLPay/molpay-mobile-xdk-reactnative-beta#3]
Is this library possible to use bank transfer with Maybank2u?

**Comment by clewlb** [comment]
@rustykey,

Thanks for reaching out. This library enables payment through Maybank2U banking method.

**Comment by rustykey** [comment]
And then, dose the Maybank2u method uses WebView?
Actually, we are using WebView with Maybank2u for payment, but there is so many issues.
For example, the WebView on iOS can't open a new window.
