### ISSUE TITLE
[Q] No channel found, please check currency value error

### ISSUE THREAD

**Issue by anniewey** [MOLPay/molpay-mobile-xdk-reactnative-beta#32]
Hi,

May I know what does this error message implies?
`{"Error":"No channel found, please check currency value"}`
The credentials and currency are correct but I get this message when call `molpay.startMolpay(details, ()=>{})`

The `details` that passed:

```
mp_amount: "130900.00"
mp_app_name: "..."
mp_bill_description: "Item - Invoice #1112222"
mp_bill_email: "name@email.com"
mp_bill_mobile: "019..."
mp_bill_name: "Name"
mp_channel: "credit"
mp_channel_editing: true
mp_country: "ID"
mp_currency: "IDR"
mp_editing_enabled: true
mp_language: "EN"
mp_merchant_ID: "..."
mp_order_ID: 1112222
mp_password: "...#"
mp_username: "..."
mp_verification_key: "..."
```

**Comment by wasddsaw** [comment]
Hi @anniewey, please report to our support care at support-sa@razer.com and attention to Mobile Team.
