### ISSUE TITLE
Dose the Maybank2u method uses WebView?

### ISSUE THREAD

**Issue by rustykey** [MOLPay/molpay-mobile-xdk-reactnative-beta#4]
Dose the Maybank2u method uses WebView?
Actually, we are using WebView with Maybank2u for payment, but there is so many issues.
For example, the WebView on iOS can't open a new window.

**Comment by clewlb** [comment]
@rustykey,

We understand your concerns and we are all agree with you about the issues if you were to make Maybank2U work within a mobile app using the webviews. And yes, we use webviews in all our XDK series, but we make sure they work for you when you use our XDK modules. That's what XDK designed and developed for, to make payment in mobile app development easy for our merchants. Why not give it a try yourself? All our XDK modules come with a sample project. If you are not our merchant yet, please contact our sales at 603-55218438 or email sales@molpay.com for more info on getting started. Thanks.

**Comment by rustykey** [comment]
@clewlb 

Thanks for the reply, 
We've made mobile app using react-native with Magento.
When I choose Maybank2u on molpay, it returns this below link
"https://www.onlinepayment.com.my/MOLPay/pay/althea/maybank2u.php"
This page is using "window.open" javascript, it doesn't work on iOS.
XDK also uses this link or another link for payment with Maybank2u?
If XDK uses another link, Can you let me know that the link?

Thanks

**Comment by clewlb** [comment]
@rustykey,

Please contact me through clement@molpay.com, we'll take the discussion further there. Thanks.
