### ISSUE TITLE
Could not find com.android.volley:volley:1.0.0 on RN 0.65

### ISSUE THREAD

**Issue by chungweileong94** [MOLPay/molpay-mobile-xdk-reactnative-beta#40]
```
> Could not find com.android.volley:volley:1.0.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/android/volley/volley/1.0.0/volley-1.0.0.pom
       - file:/Users/chungwei/.m2/repository/com/android/volley/volley/1.0.0/volley-1.0.0.pom
       - file:/Volumes/MacExtDrive/Projects/drop/node_modules/react-native/android/com/android/volley/volley/1.0.0/volley-1.0.0.pom
       - file:/Volumes/MacExtDrive/Projects/drop/node_modules/jsc-android/dist/com/android/volley/volley/1.0.0/volley-1.0.0.pom
       - https://dl.google.com/dl/android/maven2/com/android/volley/volley/1.0.0/volley-1.0.0.pom
       - https://www.jitpack.io/com/android/volley/volley/1.0.0/volley-1.0.0.pom
     Required by:
         project :app > project :molpay-mobile-xdk-reactnative-beta
```

**Comment by azmanjamlie** [comment]
Hi, How about this issue? any workaround?

**Comment by chungweileong94** [comment]
@azmanjamlie It doesn't work because jcenter is removed starting from RN 0.65, due to the [jcenter is now ready-only](https://developer.android.com/studio/build/jcenter-migration).

But this won't stop you from adding it back to your project.

```
allprojects {
    repositories {
        ...

        // TODO: Remove jcenter()
        // Started from RN 0.65, jcenter not longer include by default,
        // However, there are some packages still rely on it
        // - molpay-mobile-xdk-reactnative-beta
        jcenter()
    }
}
```

**Comment by chungweileong94** [comment]
@wankimmy I don't get why this issue is closed, does it fixed? Because I don't see any new release to address this.

**Comment by wankimmy** [comment]
> @wankimmy I don't get why this issue is closed, does it fixed? Because I don't see any new release to address this.

Hi @chungweileong94 , you may refer from this latest release https://www.npmjs.com/package/molpay-mobile-xdk-reactnative-beta

**Comment by chungweileong94** [comment]
> > @wankimmy I don't get why this issue is closed, does it fixed? Because I don't see any new release to address this.
> 
> Hi @chungweileong94 , you may refer from this latest release https://www.npmjs.com/package/molpay-mobile-xdk-reactnative-beta

Yeah, as far as I can tell, I don't think the latest release fixed the issue by looking at the source 
https://socket.dev/npm/package/molpay-mobile-xdk-reactnative-beta/files/0.32.0/android/build.gradle

**Comment by wankimmy** [comment]
@hisyamadzha may need your help to look into this

**Comment by hisyamadzha** [comment]
@chungweileong94 
You may replace jcenter() to mavenCentral()

**Comment by chungweileong94** [comment]
@hisyamadzha

> @chungweileong94 You may replace jcenter() to mavenCentral()

Nope, pretty sure it doesn't fix the problem, I did make sure I have the `mavenCentral()`,
![image](https://user-images.githubusercontent.com/15154097/162619617-6f90b25d-9395-41bf-a3e3-df0748e61090.png)

**Comment by tw0517tw** [comment]
@wankimmy @hisyamadzha I think maybe you can update the `volley` version from 1.0.0 to a newer version which is hosted in new repos to fix this

**Comment by tw0517tw** [comment]
And this become important because JCenter is down today and nobody knows when it will come back.
https://stackoverflow.com/questions/74258160/is-jcenter-down

**Comment by chungweileong94** [comment]
@wankimmy @hisyamadzha  Is there any chance that the XDK library can be open source? 
As we have encountered several issues with the package for the past few years, especially when there's a major OS update where things could break unexpectedly, and we have no choice have to either patch it or wait for the update (which could take months 🫤).

**Comment by wankimmy** [comment]
> @wankimmy @hisyamadzha Is there any chance that the XDK library can be open source? As we have encountered several issues with the package for the past few years, especially when there's a major OS update where things could break unexpectedly, and we have no choice have to either patch it or wait for the update (which could take months 🫤).

hi @chungweileong94  and @tw0517tw , you may run npm-update, we already fixed the issue, you may refer the update here

https://www.npmjs.com/package/molpay-mobile-xdk-reactnative-beta

**Comment by tw0517tw** [comment]
Thanks for your quick response @wankimmy !
