### ISSUE TITLE
Failed to build Release [Missing Release/libMOLPayXDKlib.a]

### ISSUE THREAD

**Issue by xiaohao94** [MOLPay/molpay-mobile-xdk-reactnative-beta#5]
I am failed to build release product using this library.
the problem is caused by no such file of Release-iphones/libMOLPayXDKlib.a
I have follow all the steps again and again but still failed, only debug mode is workable.
Please assist in this issue as soon as possible.

Can contact us form hylim@hermo.my or gptan@hermo.my

**Comment by LeowWH** [comment]
Hi xiaohao94, thanks for using our xdk can you reach me on Skype for more convenience way to communicate, Skype id is lelouchliew93@hotmail.com. Thanks.

**Comment by LeowWH** [comment]
Hi xiaohao94, we have fix the problem in BETA 0.9.1 please try it again and give some feedback thanks for using our XDK.
