### ISSUE TITLE
在 RN 0.73.6上build报错

### ISSUE THREAD

**Issue by th-520** [MOLPay/molpay-mobile-xdk-reactnative-beta#54]
<img width="1158" alt="image" src="https://github.com/RazerMS/Mobile-XDK-RazerMS_React_Native_Beta/assets/20639456/1d742134-ed44-489b-83ab-6914c6726492">

**Comment by th-520** [comment]
@wankimmy

**Comment by Apus03** [comment]
Please try using our new package https://www.npmjs.com/package/fiuu-mobile-xdk-reactnative to do your project. Thank

**Comment by apis17** [comment]
hi @th-520 , you may reach Telegram Developer group to get quick reply

https://github.com/RazerMS/Telegram-RMSDeveloperForum
