### ISSUE TITLE
Error running on iOS Simulator And Android Emulator 

### ISSUE THREAD

**Issue by th-520** [MOLPay/molpay-mobile-xdk-reactnative-beta#55]
With my project RN version 0.73.6

Using src/app as the root directory for Expo Router.
Android Bundled 4541ms (node_modules/expo-router/entry.js)
 LOG  [TypeError: Cannot read property 'getItem' of undefined]
 LOG  [TypeError: Cannot read property 'getItem' of undefined]
 ERROR  TypeError: Cannot read property 'setPaymentDetails' of null, js engine: hermes

<img width="484" alt="image" src="https://github.com/RazerMS/Mobile-XDK-RazerMS_React_Native_Beta/assets/20639456/d1d701fd-83be-41c1-80c5-948ce9bad2b7">

<img width="449" alt="image" src="https://github.com/RazerMS/Mobile-XDK-RazerMS_React_Native_Beta/assets/20639456/d2e4a4b6-b727-4df3-b9b9-e537778f02e9">

**Comment by th-520** [comment]
@LeowWH @wankimmy @candyyng @tekjau @FadhilRozaidi @to-ton 
Can you help me?

**Comment by Apus03** [comment]
please go to inside RN ios folder then pod install
