### ISSUE TITLE
accessing _cachedSystemAnimationFence requires the main thread' was thrown while invoking setPaymentDetails on target MOLPayReactManager with

### ISSUE THREAD

**Issue by RORrvtech** [MOLPay/molpay-mobile-xdk-reactnative-beta#8]
Occures only 1st time.
when we use app next it works fine
params (
        {
        "mp_advanced_email_validation_enabled" = 0;
        "mp_advanced_phone_validation_enabled" = 0;
        "mp_amount" = "1.1";
        "mp_app_name" = "dfg";
        "mp_bill_description" = "Order for Key Chains";
        "mp_bill_description_edit_disabled" = 0;
        "mp_bill_email" = "dfg@email.com";
        "mp_bill_email_edit_disabled" = 1;
        "mp_bill_mobile_edit_disabled" = 0;
        "mp_bill_name" ='asda';
        "mp_bill_name_edit_disabled" = 1;
        "mp_channel" = "dfg";
        "mp_channel_editing" = 0;
        "mp_country" = MY;
        "mp_currency" = MYR;
        "mp_dev_mode" = 0;
        "mp_editing_enabled" = 0;
        "mp_express_mode" = 0;
        "mp_is_escrow" = "";
        "mp_is_recurring" = 0;
        "mp_language" = EN;
        "mp_merchant_ID" = "dg";
        "mp_order_ID" = 1156;
        "mp_password" = "dfg#";
        "mp_sandbox_mode" = 0;
        "mp_username" = "dfg";
        "mp_verification_key" ='dfg';
    },
    237
)
reactConsoleErrorHandler @ ExceptionsManager.js:71
console.error @ YellowBox.js:62
logToConsole @ RCTLog.js:45
logIfNoNativeHook @ RCTLog.js:31
__callFunction @ MessageQueue.js:250
(anonymous) @ MessageQueue.js:101
__guard @ MessageQueue.js:218
callFunctionReturnFlushedQueue @ MessageQueue.js:100
(anonymous) @ debuggerWorker.js:71

**Comment by LeowWH** [comment]
Hi @RORrvtech,

Thanks for trying out our react native XDK. We have just release an update 0.13.2 please try it again. If the problem still exist you can reopen this issue anytime to inform us thanks.
