### ISSUE TITLE
Installation issue on Android

### ISSUE THREAD

**Issue by JinHoSo** [MOLPay/molpay-mobile-xdk-reactnative-beta#9]
Hi, I've got this error when I tried to install this plugin.
And I'm wondering if you are supporting seamless now?

/private/var/mobile/node_modules/molpay-mobile-xdk-reactnative-beta/android/src/main/java/com/molpayxdk/MOLPayReactPackage.java:15: error: MOLPayReactPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class MOLPayReactPackage implements ReactPackage{
       ^
1 error
:molpay-mobile-xdk-reactnative-beta:compileReleaseJavaWithJavac FAILED

**Comment by LeowWH** [comment]
Hi @JinHoSo ,

Thanks for using our XDK please be informed that if you are using RN below than 0.47.1 please follow then below instruction as documented

 Navigate to node_modules/molpay-mobile-xdk-reactnative-beta/android/src/main/java/com/molpayxdk/MOLPayReactPackage.java and add the below code.
 
     @Override
     public List<Class<? extends JavaScriptModule>> createJSModules() {
         return Collections.emptyList();
     }


> And I'm wondering if you are supporting seamless now?

About your second question please send email to our support@molpay.com to explain more details on it thanks.
